version: "3.9"
services:
  backend:
    container_name: animalfarm-backend
    build:
      context: backend
      dockerfile: dockerfile
    environment:
      DB_USER: root
      DB_PASS: root
      DB_HOST: db
    depends_on:
      - db

  frontend:
    container_name: animalfarm-frontend
    build:
      context: frontend
      dockerfile: dockerfile
    depends_on:
      - backend

  proxy:
    container_name: animalfarm-proxy
    image: envoyproxy/envoy:v1.19.1
    ports:
      - 3000:3000
    volumes:
      - ./proxy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - frontend

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: animalfarm

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/